# Typo check: https://github.com/crate-ci/typos

[files]
extend-exclude = ["go.mod", "go.sum"]

[default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
ConnTLSer = "ConnTLSer"
flate = "flate"
TestCompressFlateSerial = "TestCompressFlateSerial"
testCompressFlate = "testCompressFlate"
TestCompressFlateConcurrent = "TestCompressFlateConcurrent"
trUe = "trUe"
OPTIO = "OPTIO"
contant = "contant"
referer = "referer"
HeaderReferer = "HeaderReferer"
expectedReferer = "expectedReferer"
Referer = "Referer"
O_WRONLY = "O_WRONLY"
WRONLY = "WRONLY"
ome = "ome"
ifModifiedSice = "ifModifiedSice"
hd = "hd"
pn = "pn"